Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - mdn_query.gemspec
    - lib/mdn_query/traverse_dom.rb
Metrics/ClassLength:
  CountComments: false
  Max: 100
  Exclude:
    - test/**/*.rb
    - lib/mdn_query/traverse_dom.rb
Metrics/ModuleLength:
  CountComments: false
  Max: 100
  Exclude:
    - test/**/*.rb
Metrics/AbcSize:
  Max: 20
  Exclude:
    - lib/mdn_query/traverse_dom.rb
Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - lib/mdn_query/traverse_dom.rb
Metrics/MethodLength:
  CountComments: false
  Max: 25
  Exclude:
    - lib/mdn_query/traverse_dom.rb
Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - lib/mdn_query/traverse_dom.rb
