sudo: false
language: ruby
os:
  - linux
  - osx
cache:
  bundler: true
rvm:
  - 2.3.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
after_success:
  - bundle exec codeclimate-test-reporter
notifications:
  email: false
